version: '3.4'
services:
  io.undersoft.gwp.nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: io.undersoft.gwp.nginx-proxy
    ports:
      - '9080:80'
      - '9443:443'
    volumes:
      -  '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './shared/nginx/vhost.d:/etc/nginx/vhost.d'
      - './shared/nginx/certs:/etc/nginx/certs:ro'
    networks:
      proxy: null
      undersoft.int:
        aliases:
          - identity.sts.idp.undersoft.int
          - admin.idp.undersoft.int
          - api.admin.idp.undersoft.int
    restart: always
  io.undersoft.idp.admin:
    image: '${DOCKER_REGISTRY-}undersoft-idp-admin'
    build:
      context: .
      dockerfile: src/Undersoft.IDP.Admin/Dockerfile
    container_name: io.undersoft.idp.admin
    environment:
      - VIRTUAL_HOST=admin.idp.undersoft.int
      - 'ConnectionStrings__ConfigurationDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true;'
      - 'ConnectionStrings__PersistedGrantDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true'
      - 'ConnectionStrings__IdentityDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true'
      - 'ConnectionStrings__AdminLogDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true'
      - 'ConnectionStrings__AdminAuditLogDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true'
      - 'AdminConfiguration__IdentityAdminBaseUrl=https://admin.idp.undersoft.int'
      - 'AdminConfiguration__IdentityAdminRedirectUri=https://admin.idp.undersoft.int/signin-oidc'
      - 'AdminConfiguration__IdentityServerBaseUrl=https://identity.sts.idp.undersoft.int'
      - AdminConfiguration__RequireHttpsMetadata=false
      - 'IdentityServerData__Clients__0__ClientUri=https://admin.idp.undersoft.int'
      - 'IdentityServerData__Clients__0__RedirectUris__0=https://admin.idp.undersoft.int/signin-oidc'
      - 'IdentityServerData__Clients__0__FrontChannelLogoutUri=https://admin.idp.undersoft.int/signin-oidc'
      - 'IdentityServerData__Clients__0__PostLogoutRedirectUris__0=https://admin.idp.undersoft.int/signout-callback-oidc'
      - 'IdentityServerData__Clients__0__AllowedCorsOrigins__0=https://admin.idp.undersoft.int'
      - 'IdentityServerData__Clients__1__RedirectUris__0=https://api.admin.idp.undersoft.int/swagger/oauth2-redirect.html'
      - 'Serilog__WriteTo__1__Args__connectionString=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
    command: dotnet Undersoft.IDP.Admin /seed
    depends_on:
      - io.undersoft.dbp.pgsql
      - io.undersoft.idp.sts.identity
    volumes:
      - './shared/serilog.json:/app/serilog.json'
      - './shared/identitydata.json:/app/identitydata.json'
      - './shared/identityserverdata.json:/app/identityserverdata.json'
      - './shared/nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
    networks:
      undersoft.int: null
  io.undersoft.idp.admin.api:
    image: '${DOCKER_REGISTRY-}undersoft-idp-admin-api'
    build:
      context: .
      dockerfile: src/Undersoft.IDP.Admin.Api/Dockerfile
    container_name: io.undersoft.idp.admin.api
    environment:
      - VIRTUAL_HOST=api.admin.idp.undersoft.int
      - AdminApiConfiguration__RequireHttpsMetadata=false
      - 'AdminApiConfiguration__ApiBaseUrl=https://api.admin.idp.undersoft.int'
      - 'AdminApiConfiguration__IdentityServerBaseUrl=https://identity.sts.idp.undersoft.int'
      - 'ConnectionStrings__ConfigurationDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true;'
      - 'ConnectionStrings__PersistedGrantDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true'
      - 'ConnectionStrings__IdentityDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true'
      - 'ConnectionStrings__AdminLogDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true'
      - 'ConnectionStrings__AdminAuditLogDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - './shared/serilog.json:/app/serilog.json'
      - './shared/nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
    networks:
      undersoft.int: null
  io.undersoft.idp.sts.identity:
    image: '${DOCKER_REGISTRY-}undersoft-idp-sts-identity'
    build:
      context: .
      dockerfile: src/Undersoft.IDP.STS.Identity/Dockerfile
    container_name: io.undersoft.idp.sts.identity
    environment:
      - VIRTUAL_HOST=identity.sts.idp.undersoft.int
      - 'ConnectionStrings__ConfigurationDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true;'
      - 'ConnectionStrings__PersistedGrantDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true'
      - 'ConnectionStrings__IdentityDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Host=db; Port=7432; Database=IDP.Identity; UserId=postgres;Password=V00dkaPL; Pooling=true'
      - 'AdminConfiguration__IdentityAdminBaseUrl=https://admin.idp.undersoft.int'
      - 'IdentityServerOptions__IssuerUri=https://identity.sts.idp.undersoft.int'
      - IdentityServerOptions__Events__RaiseErrorEvents=true
      - IdentityServerOptions__Events__RaiseInformationEvents=true
      - IdentityServerOptions__Events__RaiseFailureEvents=true
      - IdentityServerOptions__Events__RaiseSuccessEvents=true
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - io.undersoft.dbp.pgsql
    volumes:
      - './shared/serilog.json:/app/serilog.json'
      - './shared/nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
    networks:
      undersoft.int:
        aliases:
          - identity.sts.idp.undersoft.int
  io.undersoft.dbp.pgsql:
    image: postgres:alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=V00dkaPL
    ports:
      - '7432:5432'
    container_name: io.undersoft.dbp.pgsql
    volumes:
      - 'io.undersoft.dbp:/var/opt/pgsql/data'
    networks:
      undersoft.int: null
  io.undersoft.tkp.adminer:
    image: adminer
    restart: always
    ports:
      - 5880:8080
    container_name: io.undersoft.tkp.adminer
    networks:
      undersoft.int: null
volumes:
  io.undersoft.dbp:
    driver: local
networks:
  proxy:
    driver: bridge
  undersoft.int:
    driver: bridge
